### ISSUE TITLE
Camera Selection

### ISSUE THREAD

**Issue by c11whaley** [UCI-HyperXite/hx9-control-system#12]

**Comment by SM-dot** [comment]
The considerations were based on the pod status we had in fall quarter. This doc has 3 options listed at the bottom - [https://docs.google.com/document/d/13u17fPWAkwlvvZ7Cfze6yx2QZs7xmpPhqkjGUDXzHMs/edit?usp=sharing]
The doc is focused on a general imaging system, we can always discuss more!
